# fly.toml app configuration file generated for fight-bot on 2023-05-28T09:07:56-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fight-bot"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  auto_rollback = true

[build]
  builder = "heroku/builder:24"
