# fly.toml file generated for fight-bot on 2022-10-18T18:37:52-04:00

app = "fight-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
